Python 3.6.1 (default, Mar 27 2017, 00:27:06) 
[GCC 6.3.1 20170306] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marcus/Public/python/ex28.py", line 1, in <module>
ValueError: too many values to unpack (expected 3)
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marcus/Public/python/ex28.py", line 1, in <module>
ValueError: too many values to unpack (expected 3)
>>> >>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marcus/Public/python/ex28.py", line 1, in <module>
ValueError: too many values to unpack (expected 3)
>>>   C-c C-cTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marcus/Public/python/ex28.py", line 1, in <module>
KeyboardInterrupt
>>>   C-c C-cTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marcus/Public/python/ex28.py", line 1, in <module>
KeyboardInterrupt
>>> 5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marcus/Public/python/ex28.py", line 1, in <module>
ValueError: not enough values to unpack (expected 3, got 1)
>>>   C-c C-c
KeyboardInterrupt
>>> 55 5 5
  File "<stdin>", line 1
    55 5 5
       ^
SyntaxError: invalid syntax
>>> 5
5
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marcus/Public/python/ex28.py", line 1, in <module>
ValueError: too many values to unpack (expected 3)
>>> 6 6 6
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marcus/Public/python/ex28.py", line 10, in <module>
NameError: name 'ltem' is not defined
>>> 1 10 1
10
>>> 1 10 2
  File "<stdin>", line 1
    1 10 2
       ^
SyntaxError: invalid syntax
>>> 1 10 2
5
>>> 1 20 2
10
>>> 1 20
  File "<stdin>", line 1
    1 20
       ^
SyntaxError: invalid syntax
>>> 1 20 3
6
>>> 23
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marcus/Public/python/ex29.py", line 4, in <module>
TypeError: '<' not supported between instances of 'str' and 'int'
>>> 34
34
22
22
99
99
87
87
101
102
23
23
4223
42
>>> 4223
23
23
34
34
101
23
23
42
>>> 